# try:
#     print(x)
# except:
#     print("I will reuse an error")

# x = 'hello'
#
# try:
#   print(x)
# except NameError:
#   print("Variable x is not defined")
# finaly:
#   print("Something else went wrong")

x = "hello"

try:
  print(x)
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")


